### ISSUE TITLE
IW+Supplementaries does not create charred/smoldering blocks

### ISSUE THREAD

**Issue by Vaskritaya** [AstralOrdana/Immersive-Weathering#270]
**Describe the bug:**
With the default configurations, the incredibly lovely charred wood blocks from Immersive Weathering do not generate alongside Supplementaries, likely due to whatever it does for its own handling for ash. If you disable ash in the supplementaries configuration, charred wood appears as expected. However, this has its own issue: IW ash does not generate. (see: issue #254 )
As such, the player must choose between ash and smoldering wood, instead of getting both as intended.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Immersive Weathering version: 1.19.2-1.2.9
Moonlight Lib version: 1.19.2-2.2.31
Fabric API / QSL / Forge version: Forge 43.2.8
Supplementaries version: 1.19.2-2.3.8

**Other mods:**
![image](https://user-images.githubusercontent.com/22992007/236658093-c3aa3aa5-1c8f-4731-a91e-eeadb91d5f47.png)

**Logs:**
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/11413941/latest.log)
[debug.log](https://github.com/AstralOrdana/Immersive-Weathering/files/11413942/debug.log)
[launcher_log.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/11413943/launcher_log.txt)

**To Reproduce:**

1. Install Forge, Moonlight lib, IW and Supplementaries.
2. Enter creative mode, build  a wooden structure, burn it. See Supplementaries ash generate, no charred blocks.
3. Pause the game and enter Supplementaries config. Disable its ash features.
4. Repeat step 2. See IW charred blocks generate, but no IW ash piles. 

**Expected behavior:**
Charred blocks to generate even with Supplementaries ash on, and IW ash to generate with Supplementaries ash off.

**Screenshots:**
The same structure burnt with different configs. Left, supplementaries ash on. Right, supplementaries ash off.
![image](https://user-images.githubusercontent.com/22992007/236657971-9d1a35fe-7482-4e9f-b975-5825e2e76834.png)

**Additional info:**
I am running minecraft with linux 6.3.1.arch1-1. I doubt that's relevant, but you can never be too safe.

**Comment by NiveStinks** [comment]
I can confirm that this issue cannot be solved by using Block Swap to exchange the different ashes.

**Comment by AstralOrdana** [comment]
i believe this was fixed in 1.2.10

**Comment by archonxgames** [comment]
Still does not seem fixed, tested with latest version of Supplementaries and Immersive Weathering at MC version 1.20.1

**Comment by Vaskritaya** [comment]
> Still does not seem fixed, tested with latest version of Supplementaries and Immersive Weathering at MC version 1.20.1

Unless I'm mistaken, IW doesn't even have ash piles anymore. With both it and supplementaries at the current version, supplementaries ash appears alongside charred blocks for me, which seems to be working as intended.
