### ISSUE TITLE
Crash involving how Leaf piles stack

### ISSUE THREAD

**Issue by thedeerirty** [AstralOrdana/Immersive-Weathering#327]
**Describe the bug:**
A crash involving players near a leaf pile (seemingly just oak)
from what the logs have told me, it seems like the amount allowed for the height of the leaf piles is a negative number, rather than the allowed values, but my configuration file has it as default still. 

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Immersive Weathering version: 2.0.0
Moonlight Lib version: 2.9.7
Fabric API / QSL / Forge version: 42.2.20 (Forge)

**Other mods:**
See the Crash report

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
[crash-2024-02-04_01.31.59-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/14154777/crash-2024-02-04_01.31.59-server.txt)
accidentally deleted the latest/debug on my server without thinking about it (folder was too full as I hadn't cleared it in a while)
I can get it again if you think's needed

**To Reproduce:**
Unsure
Player's load nearby leaf piles and the server crashes. It's never instant though - it's hard to tell what leaf piles can even be loaded

**Comment by AstralOrdana** [comment]
known issue with unknown cause, believed to be related to mod incompat because issue is not always present

**Comment by thedeerirty** [comment]
i see
anything I can do for now to fix it, or is my world sorta bricked?
and
is connector present in any other instance of this crash?

**Comment by MehVahdJukaar** [comment]
fixed

**Comment by Neshura87** [comment]
Compiled the mod using the commit that mentions fixing this, the issue is very much not fixed. Bug persists.

The way I solved it with my compiled version is changing [common/src/main/java/com/ordana/immersive_weathering/blocks/LeafPileBlock.java](https://github.com/AstralOrdana/Immersive-Weathering/commit/c7f90456a9518a334352f332566d2948818fc53e#diff-581c834f6eb192a370321213473859a5bf360564d3cf4356aec3f9527cf943e3) line 248/249 to

```java
level.setBlockAndUpdate(pos, state.setValue(AGE, age + 1)
                .setValue(LAYERS, layers <= 1 ? layers : layers - 1));
```

But I'm not sure if that is now working as intended.

**Comment by AstralOrdana** [comment]
its fixed in the dev environment, there are other issues preventing me from committing it rn though
