### ISSUE TITLE
Immersive Weathering farmland not accepting most seeds

### ISSUE THREAD

**Issue by Cyrenii** [AstralOrdana/Immersive-Weathering#335]
**Describe the bug:**
The custom farmland from this mod does not accept any seeds except melon and pumpkin. Earthen clay farmland also accepts sugarcane, which *may* be unintended, and the planted sugarcane floats a pixel above the farmland block. No other farmland accepts sugarcane.

**Versions:**
Minecraft version: 1.20.1
Immersive Weathering version: 1.20.1-2.0.0
Moonlight Lib version: forge_1.20-2.9.10
Forge version: 1.20.1-47.2.17

**Other mods:**
No mods except IW, Moonlight Lib, Supplementaries.

**Logs:**
Neither debug nor live log provide relevant information, only /gamerule randomTickSpeed being executed, the [A Seedy Place] advancement notification, and world saving during pauses.

**To Reproduce:**
1. Right click any Immersive Weathering farmland with a non-melon, non-pumpkin seed.

**Expected behavior:**
Seeds that aren't melon or pumpkin would be planted.

**Screenshots:**
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/159608700/d6727f65-974c-4d7a-888e-50010a0e7df7)
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/159608700/1b327bf2-b9c7-4d4f-ae2b-397955b4ac09)

**Comment by AstralOrdana** [comment]
this may be forge-specific, needs verification

**Comment by AstralOrdana** [comment]
should be fixed for 2.0.1, please reopen if this is not the case

**Comment by ambientNexus** [comment]
> should be fixed for 2.0.1, please reopen if this is not the case

Not the original poster, but the issue still occurs with modded crops such as the crops from Farmers Delight.

**Comment by AstralOrdana** [comment]
you can temp fix this by adding the farmlands to the minecraft dirt tag cause the fd crops use that for placement

**Comment by hypercross** [comment]
fd cabbage, rice and onion work for me but not tomatoes.

**Comment by AstralOrdana** [comment]
i believe thats because the tomatoes are hardcoded to look for vanilla farmland, not fixable on my end

edit: yep, hardcoded
https://github.com/MehVahdJukaar/FarmersDelightRefabricated/blob/1.20/src/main/java/vectorwing/farmersdelight/common/block/BuddingTomatoBlock.java#L30

**Comment by Paldiu** [comment]
This is happening for me on Fabric 1.20.1 
Mod version 2.0.3, not even vanilla wheat seeds are accepted by the mulch.

**Comment by davisssamuel** [comment]
I’m having this issue on 1.20.1 Forge 47.3.22; unable to plant vanilla crops on mulch or soaked/hydrated mulch. Mulch also does not hydrate when next to water source block.

**Comment by AstralOrdana** [comment]
working as intended, mulch doesnt grow crops and hasnt since moving to 1.20
