### ISSUE TITLE
Serene Seasons ice formation

### ISSUE THREAD

**Issue by IdkAntt** [AstralOrdana/Immersive-Weathering#386]
**Describe the Bug**
With serene seasons installed the ice that forms in biomes like the forest biomes form then melt a few seconds later. Tested it in multiple biomes and if the biome doesn't support ice in vanilla the same thing occurs.

**Versions**
Minecraft version: 1.20.1
Immersive Weathering version: 2.0.1 and 2.0.2
Moonlight Lib version: 2.12.9
Fabric API / QSL / Forge version: 47.2.0

**Other mods:**
![image_2024-08-06_150959853](https://github.com/user-attachments/assets/b3cc2bbe-1ac6-41c9-a425-03d3b671ea78)

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
[latest.log](https://github.com/user-attachments/files/16516190/latest.log)
Can't Find any of the others

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Download Serene Seasons and Immersive Weathering
2. Make a new world and play
3. wait a few minutes/ place ice in a river in a temperate biome
4. watch the ice melt in early spring

**Expected behavior:**
Ice to continue forming in the river and stick until mid or late spring.

**Screenshots:**
These are from me testing it with just the mods recommended with Immersive Weathering and Serene Seasons
![2024-08-06_15 21 34](https://github.com/user-attachments/assets/1abedf37-33b4-4f13-b0a6-2877813a2dc0)
![2024-08-06_15 21 40](https://github.com/user-attachments/assets/af37515b-342e-403a-b3bf-90ba5fe2f57c)
![2024-08-06_15 22 14](https://github.com/user-attachments/assets/01e7cab7-abda-4b22-a67d-d1a42c7186e3)
![2024-08-06_15 22 20](https://github.com/user-attachments/assets/7e371443-ccff-4628-8d4d-1ebc4776ac6f)

**Additional info:**
Here is the log with just immersive weathering and Serene Seasons.
[latest.log](https://github.com/user-attachments/files/16516261/latest.log)

**Comment by AstralOrdana** [comment]
should be fixed for 2.0.3

**Comment by RMEngelbrecht** [comment]
Sadly I will have to re-open this issue as I can still reproduce this on v2.0.3. Although it's a little hard to reproduce it with vanilla world generation, the easiest way is:
1. Generate a world without Immersive Weathering
2. Locate a Taiga biome with a body of water
3. Set weather to rain and wait for ice to form
4. Reload world with Immersive Weathering
5. Observe

Details:
Minecraft 1.20.1
Forge 47.3.10
Immersive Weathering 2.0.3
Serene Seasons 9.0.0.46
Moonlight Lib 2.13.1

Examples:
[Vanilla generation](https://github.com/user-attachments/assets/27d8c0e4-50d6-449f-84c1-27c04cac1693)
[Modded generation](https://github.com/user-attachments/assets/f62e5ffd-13b7-4ebc-968d-870fad067f63)

As you can see it's a lot easier to notice with modded generation, and in that scale it also comes with a noticeable amount of lag. Regardless though, it's also very prevalent in vanilla generation.

**Comment by aprusik** [comment]
I'm also getting this issue still. Turning up the tick speed makes it more noticeable.
