### ISSUE TITLE
Crashing with croptopia.

### ISSUE THREAD

**Issue by Lozf** [AstralOrdana/Immersive-Weathering#67]
[crash-2022-05-27_14.35.25-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/8789870/crash-2022-05-27_14.35.25-server.txt)

Also, I noticed that falling leaves no longer work with immersive weathering installed- the new version.

**Comment by AstralOrdana** [comment]
I'm fairly sure that's an issue with croptopia, i dont think theres anything I can do to fix that but I will check

**Comment by Lozf** [comment]
Ok, thanks!

**Comment by AstralOrdana** [comment]
also have you checked your config? the falling leaves seem to work fine for me

**Comment by Lozf** [comment]
Oh yeah, I mean I use the falling leaves mod, and the new version of immersive weathering with leaf fall turned off seems to stop the falling leaves mod from working as well.  Your falling leaves are cool, I just like being able to turn them down to just a few at a time.

**Comment by Lozf** [comment]
Ah- I figured the falling leaves issue out my configs on that one got reset for some reason.  Sorry about that!

**Comment by ExcessiveAmountsOfZombies** [comment]
are my leaves in some config?

**Comment by AstralOrdana** [comment]
no @ExcessiveAmountsOfZombies its that you have blocks that are leaf blocks but they dont have the persistent tag and i forgot to do a .contains check but it has that now so hopefully this should be fixed

**Comment by ExcessiveAmountsOfZombies** [comment]
oh woops, i thought I replied to the issue on my tracker haha. yea they intentionally don't have persistence for balancing reasons

**Comment by Lozf** [comment]
I actually tried the new update and it still crashes with croptopia. 
[crash-2022-05-27_20.51.19-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/8790454/crash-2022-05-27_20.51.19-server.txt)
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/8790460/latest.log)

**Comment by AstralOrdana** [comment]
okay actually fixed now, should be working in 2.5.3

**Comment by Lozf** [comment]
Sweet!  Thank you!

**Comment by AstralOrdana** [comment]
could you confirm that this has been fixed on 2.5.3?

**Comment by Lozf** [comment]
I am testing now!

**Comment by Lozf** [comment]
Ok, I went to all the places it crashed before on a new world, no crashing!

**Comment by AstralOrdana** [comment]
fantastic tysm
